profile: full

shared:
  ingress_domain: apps.$domain
  
ceip_policy_disclosed: true
buildservice:
  kp_default_repository: $HARBOR_DOMAIN/build-service/tbs
  kp_default_repository_username: $HARBOR_USER
  kp_default_repository_password: $HARBOR_PWD
  
supply_chain: basic
ootb_supply_chain_basic:
  registry:
    server: $HARBOR_DOMAIN
    repository: "tap/supply-chain"
 

contour:
  envoy:
    service:
      type: LoadBalancer
      
tap_gui:
  service_type: ClusterIP

scanning:
  metadataStore:
    url: "" # Disable embedded integration since it's deprecated

grype:
  namespace: "dev"
  targetImagePullSecret: "registry-credentials"

cnrs:
  provider: local
  domain_name: apps.source-lab.io
  # Fix domain template for TSL certficates
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

metadata_store:
  ns_for_export_app_cert: dev
  app_service_type: ClusterIP

ootb_templates:
     iaas_auth: true
     
excluded_packages:
- policy.apps.tanzu.vmware.com


# Temporay fix for 1.2
package_overlays:
- name: tap-gui
  secrets:
  - name: k8s-reader-overlay
