apiVersion: v1
kind: Pod
metadata:
  name: kaniko-tester
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/assafsauer/tap-container.git#refs/heads/lightweigt"
    - "--context-sub-path=image"
    - "--destination=asauer/tap-install:light"
    - "--build-arg"
    - "tap_release=1.5.3"
    - "--build-arg"
    - "tap_namespace=dev"
    - "--build-arg"
    - "HARBOR_USER=tanzu"
    - "--build-arg"
    - "HARBOR_PWD=xxxx"
    - "--build-arg"
    - "HARBOR_DOMAIN=hl.registriy.domain"
    - "--build-arg"
    - "INSTALL_REGISTRY_HOSTNAME=registry.tanzu.vmware.com"
    - "--build-arg"
    - "INSTALL_REGISTRY_USERNAME=email"
    - "--build-arg"
    - "INSTALL_REGISTRY_PASSWORD=xxx"
    - "--build-arg"
    - "tap_version=1.5.3"
    - "--build-arg"
    - "framework_linux_amd64=1478717"
    - "--build-arg"
    - "gui_blank_Catalog=1099786"
    - "--build-arg"
    - "gui_Yelb_Catalog=1073911"
    - "--build-arg"
    - "essential=1528454"
    - "--build-arg"
    - "VERSION=v0.28.1"
    - "--build-arg"
    - "token=xxxx"
    - "--build-arg"
    - "essential_ver=1.5.2"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred
      items:
        - key: .dockerconfigjson
          path: config.json
