apiVersion: v1
kind: Pod
metadata:
  name: kaniko-tester
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/assafsauer/service-test-pod.git#refs/heads/main"
    - "--context-sub-path=image" 
    - "--destination=asauer/tester:latest"
    env:
      - name: GIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: git-token
            key: password
      - name: GIT_USERNAME
        valueFrom:
          secretKeyRef:
            name: git-token
            key: username
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred
      items:
        - key: .dockerconfigjson
          path: config.json
