apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  serviceAccountName: my-service-account
  containers:
  - name: my-container
    image: asauer/tap-install:light
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: project-config
    command: ["/bin/sh", "-c"]
    args:
      - |
        tail -f /dev/null
