apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  serviceAccountName: my-service-account
  containers:
  - name: my-container
    image: asauer/tester:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    env:
      - name: PROJECT_ID
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: PROJECT_ID
      - name: ORG
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: ORG
      - name: ENV
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: ENV
      - name: APIGEE_TOKEN
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: APIGEE_TOKEN
      - name: SERVICE_ACCOUNT_KEY
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: SERVICE_ACCOUNT_KEY
      - name: AX_REGION
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: AX_REGION
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: REGION
      - name: ZONE
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: ZONE
      - name: NETWORK
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: NETWORK
      - name: SUBNET
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: SUBNET
      - name: GKE_CLUSTER_NAME
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: GKE_CLUSTER_NAME
      - name: GKE_CLUSTER_MACHINE_TYPE
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: GKE_CLUSTER_MACHINE_TYPE
      - name: ENV_NAME
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: ENV_NAME
      - name: ENV_GROUP_NAME
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: ENV_GROUP_NAME
      - name: DNS_NAME
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: DNS_NAME
      - name: INGRESS_TYPE
        valueFrom:
          configMapKeyRef:
            name: project-config
            key: INGRESS_TYPE
    args:
      - |
        /test/scripts/test.sh;
        tail -f /dev/null
    volumeMounts:
    - name: kubeconfig
      mountPath: /root/.kube
  volumes:
  - name: kubeconfig
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 7200

