apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-script-task
spec:
  steps:
  - name: clone-and-run-script
    image: asauer/tester:latest
    script: |
      #!/bin/sh
      git clone https://github.com/apigee/devrel.git
      cd devrel/tools/hybrid-quickstart
      ./quickstart.sh
      tail -f /dev/null
    envFrom:
    - configMapRef:
        name: project-config
